### ISSUE TITLE
some pcaps will throw a traceback

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/NetworkML#425]
```
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]: Traceback (most recent call last):
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:   File "/usr/local/bin/networkml", line 6, in <module>
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:     netml = NetworkML()
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:   File "/usr/local/lib/python3.7/site-packages/networkml/NetworkML.py", line 40, in __init__
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:     model=self.model, model_hash=self.model_hash, model_path=self.args.trained_model).eval(self.args.algorithm)
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:   File "/usr/local/lib/python3.7/site-packages/networkml/algorithms/base.py", line 150, in eval
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:     rnn_size=self.rnn_size, model_path=self.model_path, model_type=algorithm)
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:   File "/usr/local/lib/python3.7/site-packages/networkml/algorithms/sos/eval_SoSModel.py", line 29, in eval_pcap
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:     perturb_types=['random data']
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:   File "/usr/local/lib/python3.7/site-packages/networkml/parsers/pcap/session_iterator.py", line 51, in __init__
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:     random_state=0
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 2100, in train_test_split
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:     default_test_size=0.25)
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:   File "/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 1782, in _validate_shuffle_split
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]:     train_size)
2019-08-20T13:42:16+00:00 172.30.0.1 cyberreboot-networkml-v0.3.6_1566333707_116d[1659]: ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
```

**Comment by jspeed-meyers** [comment]
@cglewis, can you please provide the exact command and the pcap file or directory you used? (If that's unrealistic, just tell me.) I have a working theory (and don't mean to step on your toes @anarkiwi or duplicate your work if you have already figured this out) that this occurs when the PCAP provided produces too few flows for a given class of device. To get rid of this "error," one must provide additional PCAPs of that device type. I ran into this exact same error message when working with the SOS model recently. I fixed this problem by providing additional PCAPs of that device type. Long story short: I suspect that this is a reasonable error message and does not indicate that something is wrong with the codebase or the PCAP. Instead, for the SOS model to work properly, there must be a sufficient number of flows for each device type provided in the PCAP file or directory that is evaluated.

**Comment by cglewis** [comment]
@jspeed-meyers I think there might be a few different triggers here - for the one I ran into it was specifically only UDP traffic with ports higher than 1024 (@anarkiwi figured this out) which meant that NetworkML was throwing them out.

Regardless, the codebase should be able to handle such scenarios and not throw a traceback, but should instead log an error and send a RabbitMQ message saying such so that other systems (such as Poseidon) waiting for a response about a PCAP don't wonder what happened.

**Comment by cglewis** [comment]
Since the code base has rewritten, closing this as it's not reproducible anymore.
