### ISSUE TITLE
bad len packets throw traceback in reader.py

### ISSUE THREAD

**Issue by lostminty** [CyberReboot/NetworkML#474]
I have some pcaps I'm trialing from CIC IDS 2018 dataset. They contain a few bad len packets. 
The packets throw an array out of bounds error in reader.py when it references data[5] (Line 36) from the line passed to the  parse_packet_head(line) method. 

I've been filtering the packets with tcpdump prior to training on them to work around this. 
I tried modifying line 24 to increase the check length of data but ran into other issues that I didn't record. 

I can reproduce the data/tracebacks on request

**Comment by cglewis** [comment]
Yes, please add the traceback if you can - that is a bug that we should we gracefully handle.

**Comment by lostminty** [comment]
networkml -o train -p /home/bccc1/thur-22-2-2018/pcap
INFO:networkml.utils.model:Reading data
INFO:training_utils.py:Found 17 pcap files to read.
INFO:training_utils.py:Reading capDESKTOP (89588563 bytes) as Cap Desktop (1/17)
Traceback (most recent call last):
  File "/home/bccc1/anaconda3/envs/posml-dev/bin/networkml", line 6, in <module>
    netml = NetworkML()
  File "/home/bccc1/anaconda3/envs/posml-dev/lib/python3.6/site-packages/networkml/NetworkML.py", line 88, in __init__
    self.args.save, m, self.args.algorithm)
  File "/home/bccc1/anaconda3/envs/posml-dev/lib/python3.6/site-packages/networkml/algorithms/base.py", line 260, in train
    model.train(data_dir)
  File "/home/bccc1/anaconda3/envs/posml-dev/lib/python3.6/site-packages/networkml/utils/model.py", line 141, in train
    labels=self.labels
  File "/home/bccc1/anaconda3/envs/posml-dev/lib/python3.6/site-packages/networkml/utils/training_utils.py", line 134, in read_data
    duration=duration
  File "/home/bccc1/anaconda3/envs/posml-dev/lib/python3.6/site-packages/networkml/parsers/pcap/reader.py", line 153, in sessionizer
    packet_dict = packetizer(path)
  File "/home/bccc1/anaconda3/envs/posml-dev/lib/python3.6/site-packages/networkml/parsers/pcap/reader.py", line 125, in packetizer
    head = parse_packet_head(line)
  File "/home/bccc1/anaconda3/envs/posml-dev/lib/python3.6/site-packages/networkml/parsers/pcap/reader.py", line 36, in parse_packet_head
    destination_data = data[5].split('.')
IndexError: list index out of range

here's a pcap that does this

https://drive.google.com/file/d/1CjcVn6Sg9uJpSBHQ8EKrU3Z7bout8dI9/view?usp=sharing

**Comment by cglewis** [comment]
No longer reproducible with code rewrite.
